# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
sphinx:
  configuration: docs/conf.py
formats: all
python:
  version: 3.7
  install:
    - method: setuptools
      path: .
    - requirements: docs/requirements.txt
